# -*- coding: utf-8 -*-
"""Assignment day 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CU4-0ROL8-53jdUX6FrjM-SN2KRBzW4l
"""

x=2
y=3
result=pow(x,y)
print(result)